sometimes the robot doesn't get murdered and that's good enough for me

diff --git a/installthething b/installthething
--- a/installthething
+++ b/installthething
@@ -4,20 +4,20 @@ echo "Installing in 3." | shortcuts run "Siri say"
 echo "2." | shortcuts run "Siri say"
 echo "1." | shortcuts run "Siri say"
 
-if ping -c 1 -t 1 192.168.43.1; then
+#if ping -c 1 -t 1 192.168.43.1; then
 
-if adb devices | grep offline; then
+#if adb devices | grep offline; then
 
-killall adb
+#killall adb
 
-fi
+#fi
 
-if adb connect 192.168.43.1 | grep failed; then
+#if adb connect 192.168.43.1 | grep failed; then
 
-echo "Failed to connect" | shortcuts run "Siri say"
-exit 1
+#echo "Failed to connect" | shortcuts run "Siri say"
+#exit 1
 
-fi
+#fi
 
 if ./gradlew installDebug; then
     echo "Installation complete!" | shortcuts run "Siri say"
@@ -25,8 +25,8 @@ else
     afplay -v 2 innovation.m4a
 fi
 
-else
+#else
 
-echo "Control hub is disconnected." | shortcuts run "Siri say"
+#echo "Control hub is disconnected." | shortcuts run "Siri say"
 
-fi
+#fi
